version: '2.3'


services:
#  app:
#    image: 'selina:latest'
#    build:
#      context: .
#    container_name: app
#    depends_on:
#      - db

  db:
    image: "postgres:13.1"
    container_name: "postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: selina
    ports:
      - "5432:5432"
#    volumes:
#      - db-data:/var/lib/postgresql/data  # PostgreSQL будут сохраняться внутри контейнера в каталоге /var/lib/postgresql/data
#
#
#volumes:
#  db-data:


