version: '2.3'

services:
#  app:
#    image: 'selina:latest'
#    build:
#      context: .
#    container_name: app
#    depends_on:
#      - db

  db:
    image: "postgres:13.1"
    container_name: "postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: selina
    ports:
      - "5432:5432"

  python_ml:
    image: python-ml-service
    container_name: "python-ml-service"
    restart: always
    ports:
      - "8080:8080"
